"""Initial schema

Revision ID: a3536f8a2d84
Revises: d059ac677a19
Create Date: 2026-04-21 16:46:14.846619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3536f8a2d84'
down_revision = 'd059ac677a19'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
